### ISSUE TITLE
[PW-3985]Pay By Link support

### ISSUE THREAD

**Issue by jleclanche** [Adyen/adyen-python-api-library#124]
It doesn't look like the python sdk has a method to request a payment link.

The added issue is that even by calling `adyen.checkout.client.call_checkout_api({...}, "paymentLinks")`, an error is raised because the return code for the paymentLinks API is `201 CREATED` rather than `200 OK`, which the library interprets as an error code.

**Comment by AlexandrosMor** [comment]
Hello @jleclanche,

Thank you for raising this issue. Checking the code the issue is in the [handle response](https://github.com/Adyen/adyen-python-api-library/blob/ed1c05c3a9087a7d29fd5cc460c82f602dfd41fc/Adyen/client.py#L586) method. It checks if only the response is 200. We created an internal ticket for this issue. If you like you can open a pull request which can review and include it to the next release.

regards,
Alexandros

**Comment by jillingk** [comment]
Hi @jleclanche,

I just created a PR to add support for payment by link. Also the error for response code 201 has been fixed already in case you hadn't noticed.

Best, Jilling
Adyen
